name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install TypeScript types for Node.js
      run: npm install --save-dev @types/node

    - name: Build TypeScript
      run: npm run build

    - name: Run application
      run: npm run start
